/*
 * generated by Xtext 2.17.0
 */
package com.zazuko.apitesting.dsl.ide


/**
 * Use this class to register ide components.
 */
class ApiTestingDslIdeModule extends AbstractApiTestingDslIdeModule {
}
