/**
 * generated by Xtext 2.17.0
 */
package com.zazuko.apitesting.dsl.ide;

import com.zazuko.apitesting.dsl.ide.AbstractApiTestingDslIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class ApiTestingDslIdeModule extends AbstractApiTestingDslIdeModule {
}
