/**
 * generated by Xtext 2.17.0
 */
package com.zazuko.apitesting.dsl.apiTestingDsl.impl;

import com.zazuko.apitesting.dsl.apiTestingDsl.ApiTestingDslPackage;
import com.zazuko.apitesting.dsl.apiTestingDsl.ClassLevelAssertion;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Class Level Assertion</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ClassLevelAssertionImpl extends MinimalEObjectImpl.Container implements ClassLevelAssertion
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ClassLevelAssertionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ApiTestingDslPackage.Literals.CLASS_LEVEL_ASSERTION;
  }

} //ClassLevelAssertionImpl
