grammar com.zazuko.apitesting.dsl.ApiTestingDsl with org.eclipse.xtext.common.Terminals

generate apiTestingDsl "http://www.zazuko.com/apitesting/dsl/ApiTestingDsl"

Model:
    (elements+=Element)*;
	
Element:
	ClassBlock;
	
ClassBlock:
	'With' 'Class' name=STRING '{'
		(assertions+=ClassLevelAssertion)*
	'}';
	
ClassLevelAssertion:
	PropertyAssertion
;

PropertyAssertion:
	'Expect' 'Property' name=STRING
;
