/*
 * generated by Xtext 2.17.0
 */
package com.zazuko.apitesting.dsl


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class ApiTestingDslRuntimeModule extends AbstractApiTestingDslRuntimeModule {
}
