/*
 * generated by Xtext 2.17.0
 */
package com.zazuko.apitesting.dsl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class ApiTestingDslStandaloneSetup extends ApiTestingDslStandaloneSetupGenerated {

	def static void doSetup() {
		new ApiTestingDslStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
