/*
 * generated by Xtext 2.17.0
 */
package com.zazuko.apitesting.dsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractApiTestingDslScopeProvider extends DelegatingScopeProvider {
}
