/*
 * generated by Xtext 2.17.0
 */
package com.zazuko.apitesting.dsl.parser.antlr;

import com.google.inject.Inject;
import com.zazuko.apitesting.dsl.parser.antlr.internal.InternalApiTestingDslParser;
import com.zazuko.apitesting.dsl.services.ApiTestingDslGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class ApiTestingDslParser extends AbstractAntlrParser {

	@Inject
	private ApiTestingDslGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalApiTestingDslParser createParser(XtextTokenStream stream) {
		return new InternalApiTestingDslParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public ApiTestingDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(ApiTestingDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
