/*
 * generated by Xtext 2.17.0
 */
package com.zazuko.apitesting.dsl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class ApiTestingDslAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("com/zazuko/apitesting/dsl/parser/antlr/internal/InternalApiTestingDsl.tokens");
	}
}
