/**
 * generated by Xtext 2.17.0
 */
package com.zazuko.apitesting.dsl.apiTestingDsl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see com.zazuko.apitesting.dsl.apiTestingDsl.ApiTestingDslFactory
 * @model kind="package"
 * @generated
 */
public interface ApiTestingDslPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "apiTestingDsl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.zazuko.com/apitesting/dsl/ApiTestingDsl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "apiTestingDsl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  ApiTestingDslPackage eINSTANCE = com.zazuko.apitesting.dsl.apiTestingDsl.impl.ApiTestingDslPackageImpl.init();

  /**
   * The meta object id for the '{@link com.zazuko.apitesting.dsl.apiTestingDsl.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.zazuko.apitesting.dsl.apiTestingDsl.impl.ModelImpl
   * @see com.zazuko.apitesting.dsl.apiTestingDsl.impl.ApiTestingDslPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__ELEMENTS = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link com.zazuko.apitesting.dsl.apiTestingDsl.impl.ElementImpl <em>Element</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.zazuko.apitesting.dsl.apiTestingDsl.impl.ElementImpl
   * @see com.zazuko.apitesting.dsl.apiTestingDsl.impl.ApiTestingDslPackageImpl#getElement()
   * @generated
   */
  int ELEMENT = 1;

  /**
   * The number of structural features of the '<em>Element</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ELEMENT_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link com.zazuko.apitesting.dsl.apiTestingDsl.impl.ClassBlockImpl <em>Class Block</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see com.zazuko.apitesting.dsl.apiTestingDsl.impl.ClassBlockImpl
   * @see com.zazuko.apitesting.dsl.apiTestingDsl.impl.ApiTestingDslPackageImpl#getClassBlock()
   * @generated
   */
  int CLASS_BLOCK = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLASS_BLOCK__NAME = ELEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Class Block</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLASS_BLOCK_FEATURE_COUNT = ELEMENT_FEATURE_COUNT + 1;


  /**
   * Returns the meta object for class '{@link com.zazuko.apitesting.dsl.apiTestingDsl.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see com.zazuko.apitesting.dsl.apiTestingDsl.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link com.zazuko.apitesting.dsl.apiTestingDsl.Model#getElements <em>Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Elements</em>'.
   * @see com.zazuko.apitesting.dsl.apiTestingDsl.Model#getElements()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Elements();

  /**
   * Returns the meta object for class '{@link com.zazuko.apitesting.dsl.apiTestingDsl.Element <em>Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Element</em>'.
   * @see com.zazuko.apitesting.dsl.apiTestingDsl.Element
   * @generated
   */
  EClass getElement();

  /**
   * Returns the meta object for class '{@link com.zazuko.apitesting.dsl.apiTestingDsl.ClassBlock <em>Class Block</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Class Block</em>'.
   * @see com.zazuko.apitesting.dsl.apiTestingDsl.ClassBlock
   * @generated
   */
  EClass getClassBlock();

  /**
   * Returns the meta object for the attribute '{@link com.zazuko.apitesting.dsl.apiTestingDsl.ClassBlock#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see com.zazuko.apitesting.dsl.apiTestingDsl.ClassBlock#getName()
   * @see #getClassBlock()
   * @generated
   */
  EAttribute getClassBlock_Name();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  ApiTestingDslFactory getApiTestingDslFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link com.zazuko.apitesting.dsl.apiTestingDsl.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.zazuko.apitesting.dsl.apiTestingDsl.impl.ModelImpl
     * @see com.zazuko.apitesting.dsl.apiTestingDsl.impl.ApiTestingDslPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__ELEMENTS = eINSTANCE.getModel_Elements();

    /**
     * The meta object literal for the '{@link com.zazuko.apitesting.dsl.apiTestingDsl.impl.ElementImpl <em>Element</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.zazuko.apitesting.dsl.apiTestingDsl.impl.ElementImpl
     * @see com.zazuko.apitesting.dsl.apiTestingDsl.impl.ApiTestingDslPackageImpl#getElement()
     * @generated
     */
    EClass ELEMENT = eINSTANCE.getElement();

    /**
     * The meta object literal for the '{@link com.zazuko.apitesting.dsl.apiTestingDsl.impl.ClassBlockImpl <em>Class Block</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see com.zazuko.apitesting.dsl.apiTestingDsl.impl.ClassBlockImpl
     * @see com.zazuko.apitesting.dsl.apiTestingDsl.impl.ApiTestingDslPackageImpl#getClassBlock()
     * @generated
     */
    EClass CLASS_BLOCK = eINSTANCE.getClassBlock();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CLASS_BLOCK__NAME = eINSTANCE.getClassBlock_Name();

  }

} //ApiTestingDslPackage
