/**
 * generated by Xtext 2.17.0
 */
package com.zazuko.apitesting.dsl.apiTestingDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Class Block</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.zazuko.apitesting.dsl.apiTestingDsl.ClassBlock#getName <em>Name</em>}</li>
 * </ul>
 *
 * @see com.zazuko.apitesting.dsl.apiTestingDsl.ApiTestingDslPackage#getClassBlock()
 * @model
 * @generated
 */
public interface ClassBlock extends Element
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see com.zazuko.apitesting.dsl.apiTestingDsl.ApiTestingDslPackage#getClassBlock_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link com.zazuko.apitesting.dsl.apiTestingDsl.ClassBlock#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

} // ClassBlock
