/**
 * generated by Xtext 2.17.0
 */
package com.zazuko.apitesting.dsl.apiTestingDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Element</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see com.zazuko.apitesting.dsl.apiTestingDsl.ApiTestingDslPackage#getElement()
 * @model
 * @generated
 */
public interface Element extends EObject
{
} // Element
