/**
 * generated by Xtext 2.17.0
 */
package com.zazuko.apitesting.dsl.ui;

import com.zazuko.apitesting.dsl.ui.AbstractApiTestingDslUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class ApiTestingDslUiModule extends AbstractApiTestingDslUiModule {
  public ApiTestingDslUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
