/**
 * generated by Xtext 2.17.0
 */
package com.zazuko.apitesting.dsl.validation;

import com.zazuko.apitesting.dsl.validation.AbstractApiTestingDslValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class ApiTestingDslValidator extends AbstractApiTestingDslValidator {
}
