/*
 * generated by Xtext 2.17.0
 */
package com.zazuko.apitesting.dsl.serializer;

import com.google.inject.Inject;
import com.zazuko.apitesting.dsl.apiTestingDsl.ApiTestingDslPackage;
import com.zazuko.apitesting.dsl.apiTestingDsl.ClassBlock;
import com.zazuko.apitesting.dsl.apiTestingDsl.Model;
import com.zazuko.apitesting.dsl.apiTestingDsl.PropertyAssertion;
import com.zazuko.apitesting.dsl.services.ApiTestingDslGrammarAccess;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;

@SuppressWarnings("all")
public class ApiTestingDslSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private ApiTestingDslGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == ApiTestingDslPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case ApiTestingDslPackage.CLASS_BLOCK:
				sequence_ClassBlock(context, (ClassBlock) semanticObject); 
				return; 
			case ApiTestingDslPackage.MODEL:
				sequence_Model(context, (Model) semanticObject); 
				return; 
			case ApiTestingDslPackage.PROPERTY_ASSERTION:
				sequence_PropertyAssertion(context, (PropertyAssertion) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * Contexts:
	 *     Element returns ClassBlock
	 *     ClassBlock returns ClassBlock
	 *
	 * Constraint:
	 *     (name=STRING assertions+=ClassLevelAssertion* hatch=HATCH?)
	 */
	protected void sequence_ClassBlock(ISerializationContext context, ClassBlock semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Model returns Model
	 *
	 * Constraint:
	 *     elements+=Element+
	 */
	protected void sequence_Model(ISerializationContext context, Model semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     ClassLevelAssertion returns PropertyAssertion
	 *     PropertyAssertion returns PropertyAssertion
	 *
	 * Constraint:
	 *     (name=STRING assertions+=ClassLevelAssertion* hatch=HATCH?)
	 */
	protected void sequence_PropertyAssertion(ISerializationContext context, PropertyAssertion semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
}
