/**
 * generated by Xtext 2.17.0
 */
package com.zazuko.apitesting.dsl.ui.contentassist;

import com.zazuko.apitesting.dsl.ui.contentassist.AbstractApiTestingDslProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class ApiTestingDslProposalProvider extends AbstractApiTestingDslProposalProvider {
}
