/**
 * generated by Xtext 2.17.0
 */
package com.zazuko.apitesting.dsl;

import com.zazuko.apitesting.dsl.ApiTestingDslStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class ApiTestingDslStandaloneSetup extends ApiTestingDslStandaloneSetupGenerated {
  public static void doSetup() {
    new ApiTestingDslStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
